server:
  port: 9092

logging:
  level:
    com: debug

kafka:
  server: '59.110.171.203:9092,47.93.97.114:9092,39.105.26.134:9092'

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 为了兼容swagger3.0 和 springboot2.6.x