topicName: nike

spring:
  kafka:
    bootstrap-servers: '59.110.171.203:9092,47.93.97.114:9092,39.105.26.134:9092'
    producer:
      key-serializer: 'org.apache.kafka.common.serialization.StringSerializer'
      value-serializer: 'org.springframework.kafka.support.serializer.JsonSerializer'
      acks: all
      retries: 5
      compression-type: none
      batch-size: 16384
      properties:
        linger.ms: 1000
        max.in.flight.requests.per.connection: 1
      ssl:
        trust-store-certificates:



    consumer:
      group-id: "erick-16:25"
      key-deserializer: 'org.apache.kafka.common.serialization.StringDeserializer'
      value-deserializer: 'org.springframework.kafka.support.serializer.JsonDeserializer'
      max-poll-records: 500
      auto-offset-reset: earliest
      heartbeat-interval: 3000
      enable-auto-commit: false
      isolation-level: read_committed
